name = "xion-assistant-api"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[dev]
host = "localhost"
port = 8787

[[d1_databases]]
binding = "DB"
database_name = "xion-assistant"
database_id = "dde69fd1-0526-4216-897f-8954ce44b8a9"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "RELEASES"
bucket_name = "xion-assistant-releases"
